### ISSUE TITLE
looks like parsing url is not working

### ISSUE THREAD

**Issue by krishna01012002** [Workable/rabbit-queue#39]
Hi 
I am unable to authenticate. Please help me

Running rabbitmq server using kubectl on macos. 

I am able to launch **UI** and able to see exchanges and queues

Running cluster :  **kubectl port-forward rabbitmq-0 15672**

Code: 

**const rabbit = new Rabbit("amqp://my-user:qDq3x7DePzLyXuNnxUrdGwbvn9wF9ncu@localhost");**

Error: 

 Error: **Handshake terminated by server: 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."**
           at afterStartOk (/Users/kdeergasi/Documents/transactionexport/scp-testing-uat-tests/node_modules/amqplib/lib/connection.js:220:12)
           at /Users/kdeergasi/Documents/transactionexport/scp-testing-uat-tests/node_modules/amqplib/lib/connection.js:160:12
           at Socket.recv (/Users/kdeergasi/Documents/transactionexport/scp-testing-uat-tests/node_modules/amqplib/lib/connection.js:499:12)
           at Object.onceWrapper (events.js:421:28)
           at Socket.emit (events.js:315:20)
           at Socket.EventEmitter.emit (domain.js:483:12)
           at emitReadable_ (_stream_readable.js:555:12)
           at processTicksAndRejections (internal/process/task_queues.js:83:21)

**Comment by krishna01012002** [comment]
it was resolved..
