### ISSUE TITLE
TimeOut issue for getTopicReply and getReply 

### ISSUE THREAD

**Issue by krishna01012002** [Workable/rabbit-queue#40]
Hi 
I tried using both getTopicReply and getReply but getting Timeout issue. Kindly help me on the same issue

 const reply = await rabbit.getReply("order-listener-queue",
          { test: "data" }, { correlationId: "1" });

const reply = await rabbit.getTopicReply("routingkey",
          { test: "data" }, { correlationId: "1" }, "" , 1000);

Error:

  Error: Timed out
           at Function.<anonymous> (tests/node_modules/rabbit-queue/ts/queue.ts:179:40)
           at Generator.next (<anonymous>)
           at /node_modules/rabbit-queue/js/queue.js:8:71
           at new Promise (<anonymous>)
           at __awaiter (//node_modules/rabbit-queue/js/queue.js:4:12)
           at Function.getReply (s/node_modules/rabbit-queue/js/queue.js:166:16)
           at Rabbit.<anonymous> (/s/node_modules/rabbit-queue/ts/rabbit.ts:173:24)
           at Generator.next (<anonymous>)
           at fulfilled (/node_modules/rabbit-queue/js/rabbit.js:5:58)
           at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by krishna01012002** [comment]
I am new to rabbitMQ
